### ISSUE TITLE
[bug] with Paladin things 

### ISSUE THREAD

**Issue by Slabington** [driesceuppens/Avrae_things#12]
**Describe the bug**
Error evaluating expression: Expecting ':' delimiter: line 1 column 7 (char 6)

**To Reproduce**
1. Type !conquest presence 
2. Read the error message 

**Expected behavior**
It to use the channel divinity for the subcladd

**Screenshots**
I have one but idk how to.send my screenshot here My username on discord is Toxus#0896

**Additional context**
I tried the other conquest commands and got the same error message

**Comment by driesceuppens** [comment]
This error is caused by setting the subclass cvar incorrectly, unless it is a valid JSON map the paladin aliases are not guaranteed to work. 
After some testing I believe you need to replace a `,` with a `:` in the cvar to make the alias work again
